AWSTemplateFormatVersion: 2010-09-09
Description: Template for creation  a S3 web site
Parameters:
  HostedZone:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name
  SiteName:
    Type: String
    Description: The site name (www, demo, ftp and etc.)
    AllowedPattern: (?!-)[a-zA-Z0-9-]{1,63}(?<!-)
    ConstraintDescription: must be a valid site name 
Resources:
  S3BucketForWebSite:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["", [!Ref SiteName, ".", !Ref HostedZone]]
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: "S3BucketForWebSite"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: ["s3:GetObject"]
            Principal: "*"
            Resource: !Join ["", ["arn:aws:s3:::", !Ref S3BucketForWebSite, "/*"]]