AWSTemplateFormatVersion: 2010-09-09
Description: Template for creation  a S3 web site

Parameters:
  HostedZone:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<![-.])
    ConstraintDescription: must be a valid DNS zone name (without trailing dot)
  SiteName:
    Type: String
    Description: The site name (www, demo, ftp and etc.)
    AllowedPattern: (?!-)[a-zA-Z0-9-]{1,63}(?<!-)
    ConstraintDescription: must be a valid site name

Mappings:
  RegionMap:
    us-east-1:
      endpoint: "s3-website-us-east-1.amazonaws.com."
      hzid: "Z3AQBSTGFYJSTF"
    us-east-2:
      endpoint: "s3-website.us-east-2.amazonaws.com."
      hzid: "Z2O1EMRO9K5GLX"
    us-west-1:
      endpoint: "s3-website-us-west-1.amazonaws.com."
      hzid: "Z2F56UZL2M1ACD"
    us-west-2:
      endpoint: "s3-website-us-west-2.amazonaws.com."
      hzid: "Z3BJ6K6RIION7M"
    eu-west-1:
      endpoint: "s3-website-eu-west-1.amazonaws.com."
      hzid: "Z1BKCTXD74EZPE"
    eu-west-2:
      endpoint: "s3-website-eu-west-2.amazonaws.com."
      hzid: "Z3GKZC51ZF0DB4"
    eu-west-3:
      endpoint: "s3-website-eu-west-3.amazonaws.com."
      hzid: "Z3R1K369G5AVDG"
    eu-central-1: 
      endpoint: "s3-website-eu-central-1.amazonaws.com."
      hzid: "Z21DNDUVLTQW6Q"
    eu-north-1:
      endpoint: "s3-website-eu-north-1.amazonaws.com."
      hzid: "Z3BAZG2TWCNX0D"
    ap-northeast-1:
      endpoint: "s3-website-ap-northeast-1.amazonaws.com."
      hzid: "Z2M4EHUR26P7ZW"
    ap-northeast-2:
      endpoint: "s3-website-ap-northeast-2.amazonaws.com."
      hzid: "Z3W03O7B5YMIYP"
    ap-northeast-3:
      endpoint: "s3-website-ap-northeast-3.amazonaws.com."
      hzid: "Z2YQB5RD63NC85"
    ap-southeast-1:
      endpoint: "s3-website-ap-southeast-1.amazonaws.com."
      hzid: "Z3O0J2DXBE1FTB"
    ap-southeast-2:
      endpoint: "s3-website-ap-southeast-2.amazonaws.com."
      hzid: "Z1WCIGYICN2BYD"
    ap-south-1:
      endpoint: "s3-website-ap-south-1.amazonaws.com."
      hzid: "Z11RGJOFQNVJUP"
    ap-east-1:
      endpoint: "s3-website-ap-east-1.amazonaws.com."
      hzid: "ZNB98KWMFR0R6"
    ca-central-1:
      endpoint: "s3-website-ca-central-1.amazonaws.com."
      hzid: "Z1QDHH18159H29"
    sa-east-1: 
      endpoint: "s3-website-sa-east-1.amazonaws.com."
      hzid: "Z7KQH4QJS55SO"
    me-south-1:
      endpoint: "s3-website.me-south-1.amazonaws.com.cn."
      hzid: "Z1MPMWCPA7YB62"

Resources:
  S3BucketForWebSite:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["", [!Ref SiteName, ".", !Ref HostedZone]]
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: "S3BucketForWebSite"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: ["s3:GetObject"]
            Principal: "*"
            Resource: !Join ["", ["arn:aws:s3:::", !Ref S3BucketForWebSite, "/*"]]
  WebSiteDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Join ["", [!Ref HostedZone, "."]]
      Name: !Ref S3BucketForWebSite
      Type: "A"
      AliasTarget:
        HostedZoneId: !FindInMap [RegionMap, !Ref "AWS::Region", hzid]
        DNSName: !FindInMap [RegionMap, !Ref "AWS::Region", endpoint]